const STORE_TYPE = "ROUTE";

export const ROUTE_REQUEST = `${STORE_TYPE}/ROUTE_REQUEST`;
export const ROUTE_SUCCESS = `${STORE_TYPE}/ROUTE_SUCCESS`;
export const ROUTE_FAILURE = `${STORE_TYPE}/ROUTE_FAILURE`;
export const ROUTE_CLEAR = `${STORE_TYPE}/ROUTE_CLEAR`;