const STORE_TYPE = "ADDRESSES";

export const ADDRESS_LIST_REQUEST = `${STORE_TYPE}/ADDRESS_LIST_REQUEST`;
export const ADDRESS_LIST_SUCCESS = `${STORE_TYPE}/ADDRESS_LIST_REQUEST`;
export const ADDRESS_LIST_FAILURE = `${STORE_TYPE}/ADDRESS_LIST_REQUEST`;