const STORE_TYPE = ["auth", "signin", "savecard", "getcard"];

export const CHECK_IS_LOGIN = `${STORE_TYPE[0]}/CHECK_IS_LOGIN`;
export const LOGIN_REQUEST = `${STORE_TYPE[0]}/LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `${STORE_TYPE[0]}/LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${STORE_TYPE[0]}/LOGIN_FAILURE`;

export const REGISTER_REQUEST = `${STORE_TYPE[1]}/REGISTER_REQUEST`;
export const REGISTER_SUCCESS = `${STORE_TYPE[1]}/REGISTER_SUCCESS`;
export const REGISTER_FAILURE = `${STORE_TYPE[1]}/REGISTER_FAILURE`;
export const LOGOUT = `${STORE_TYPE[1]}/LOGOUT`;

export const CARD_SAVE_REQUEST = `${STORE_TYPE[2]}/CARD_SAVE_REQUEST`;
export const CARD_SAVE_SUCCESS = `${STORE_TYPE[2]}/CARD_SAVE_SUCCESS`;

export const CARD_GET_REQUEST = `${STORE_TYPE[3]}/CARD_GET_REQUEST`;
export const CARD_GET_SUCCESS = `${STORE_TYPE[3]}/CARD_GET_SUCCESS`;
export const CARD_FAILURE = `${STORE_TYPE[3]}/CARD_FAILURE`;
export const CHECK_IS_CARD = `${STORE_TYPE[3]}/CHECK_IS_CARD`;


