const STORE_TYPE = "REGISTRATION";

export const REGISTER_REQUEST = `${STORE_TYPE}/REGISTER_REQUEST`;
export const REGISTER_SUCCESS = `${STORE_TYPE}/REGISTER_SUCCESS`;
export const REGISTER_FAILURE = `${STORE_TYPE}/REGISTER_FAILURE`;