const STORE_TYPE = "AUTH";

export const CHECK_IS_LOGIN = `${STORE_TYPE}/CHECK_IS_LOGIN`;
export const LOGIN_REQUEST = `${STORE_TYPE}/LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `${STORE_TYPE}/LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${STORE_TYPE}/LOGIN_FAILURE`;
export const LOGOUT = `${STORE_TYPE}/LOGOUT`;