const STORE_TYPE = "CARD";

export const CARD_SAVE_REQUEST = `${STORE_TYPE}/CARD_SAVE_REQUEST`;
export const CARD_SAVE_SUCCESS = `${STORE_TYPE}/CARD_SAVE_SUCCESS`;

export const CARD_GET_REQUEST = `${STORE_TYPE}/CARD_GET_REQUEST`;
export const CARD_GET_SUCCESS = `${STORE_TYPE}/CARD_GET_SUCCESS`;
export const CARD_FAILURE = `${STORE_TYPE}/CARD_FAILURE`;
export const CHECK_IS_CARD = `${STORE_TYPE}/CHECK_IS_CARD`;
export const IS_CARD_UPDATE = `${STORE_TYPE}/IS_CARD_UPDATE`;